services:
  - type: web
    name: pdftodoc-backend
    env: node
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && node server.js"
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: "<YOUR_MONGO_URI>"
    preDeployCommand: |
      apt-get update && apt-get install -y python3-pip
      pip3 install pdf2docx
